// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: command.proto

package net.cloudcentrik.autolink.common.proto;

public interface CommandRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:command.CommandRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string commandId = 1;</code>
   * @return The commandId.
   */
  java.lang.String getCommandId();
  /**
   * <code>string commandId = 1;</code>
   * @return The bytes for commandId.
   */
  com.google.protobuf.ByteString
      getCommandIdBytes();

  /**
   * <code>string tenantId = 2;</code>
   * @return The tenantId.
   */
  java.lang.String getTenantId();
  /**
   * <code>string tenantId = 2;</code>
   * @return The bytes for tenantId.
   */
  com.google.protobuf.ByteString
      getTenantIdBytes();

  /**
   * <code>.command.CommandType commandType = 3;</code>
   * @return The enum numeric value on the wire for commandType.
   */
  int getCommandTypeValue();
  /**
   * <code>.command.CommandType commandType = 3;</code>
   * @return The commandType.
   */
  net.cloudcentrik.autolink.common.proto.CommandType getCommandType();
}
