// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: command.proto

package net.cloudcentrik.autolink.common.proto;

public final class CommandProtos {
  private CommandProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_command_CommandRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_command_CommandRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_command_CommandResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_command_CommandResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rcommand.proto\022\007command\"`\n\016CommandReque" +
      "st\022\021\n\tcommandId\030\001 \001(\t\022\020\n\010tenantId\030\002 \001(\t\022" +
      ")\n\013commandType\030\003 \001(\0162\024.command.CommandTy" +
      "pe\"g\n\017CommandResponse\022\021\n\tcommandId\030\001 \001(\t" +
      "\022-\n\rcommandStatus\030\002 \001(\0162\026.command.Comman" +
      "dStatus\022\022\n\nserverInfo\030\003 \001(\t*N\n\rCommandSt" +
      "atus\022\013\n\007STARTED\020\000\022\n\n\006FINISH\020\001\022\n\n\006FAILED\020" +
      "\003\022\013\n\007WAITING\020\004\022\013\n\007UNKNOWN\020\005*\203\001\n\013CommandT" +
      "ype\022\022\n\016IMPORT_PRODUCT\020\000\022\022\n\016EXPORT_PRODUC" +
      "T\020\001\022\020\n\014IMPORT_ORDER\020\002\022\020\n\014EXPORT_ORDER\020\003\022" +
      "\023\n\017IMPORT_CUSTOMER\020\004\022\023\n\017EXPORT_CUSTOMER\020" +
      "\005B9\n&net.cloudcentrik.autolink.common.pr" +
      "otoB\rCommandProtosP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_command_CommandRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_command_CommandRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_command_CommandRequest_descriptor,
        new java.lang.String[] { "CommandId", "TenantId", "CommandType", });
    internal_static_command_CommandResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_command_CommandResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_command_CommandResponse_descriptor,
        new java.lang.String[] { "CommandId", "CommandStatus", "ServerInfo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
